apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedrooliveira-deployment-api
  namespace: pedrooliveira
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedrooliveira-api
  template:
    metadata:
      labels:
        app: pedrooliveira-api
    spec:
      volumes:
      - name: project2-pv-pedrooliveira
        persistentVolumeClaim:
          claimName: project2-pvc-pedrooliveira
      
      containers:
          - name: pedrooliveira-recommender
            image: freitaas/api:0.1
            imagePullPolicy: Always
            volumeMounts:
            - name: project2-pv-pedrooliveira
              mountPath: /app/data/
