apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: pedrooliveira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-image-updater
  template:
    metadata:
      labels:
        app: argocd-image-updater
    spec:
      containers:
      - name: argocd-image-updater
        image: argoproj/argocd-image-updater:latest
        env:
        - name: REGISTRY_CONFIG_MAP
          value: argocd-image-updater-config
