apiVersion: batch/v1
kind: Job
metadata:
  name: pedrooliveira-job-ml-TESTE
  namespace: pedrooliveira
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: project2-pv-pedrooliveira
          persistentVolumeClaim:
            claimName: project2-pvc-pedrooliveira

        - name: datasets
          hostPath:
            path: "/home/datasets/"
            
      containers:
        - name: pedrooliveira-ml
          image: freitaas/ml:latest
          imagePullPolicy: Always
          command: ["python3", "ModelManagment.py", "-t", "2023_spotify_ds1.csv"]
          volumeMounts:
          - name: project2-pv-pedrooliveira
            mountPath: "/app/project2-pv/"
          - name: datasets
            mountPath: "/app/data/"
