apiVersion: batch/v1
kind: Job
metadata:
  name: pedrooliveira-job-ml
  namespace: pedrooliveira
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: project2-pv-pedrooliveira
          persistentVolumeClaim:
            claimName: project2-pvc-pedrooliveira

        - name: datasets
          hostPath:
            path: "/home/datasets/"
            
      containers:
        - name: pedrooliveira-ml
          image: freitaas/ml:0.1
          imagePullPolicy: Always
          volumeMounts:
          - name: project2-pv-pedrooliveira
            mountPath: /app/project2-pv/
          - name: datasets
            mountPath: "/app/data/"
