apiVersion: batch/v1
kind: CronJob
metadata:
  name: pedrooliveira-job-ml
  namespace: pedrooliveira
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: project2-pv-pedrooliveira
          persistentVolumeClaim:
            claimName: project2-pvc-pedrooliveira
        - name: dataset
          hostPath:
            path: /home/datasets/

      containers:
        - name: pedrooliveira-ml
          image: freitaas/ml:0.1
          imagePullPolicy: Always
          volumeMounts:
          - name: project2-pv-pedrooliveira
            mountPath: /home/pedrooliveira/project2-pv
          - name: dataset
            mountPath: /app/data
