name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd $GITHUB_WORKSPACE
        ls
        docker build . --file API/Dockerfile --tag freitaas/api:0.1
