name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        echo "VERSION_DOCKER_IMAGES=2" >> $GITHUB_ENV
        echo ${{vars.VERSION_DOCKER_IMAGES}}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd $GITHUB_WORKSPACE
        docker build . --file API/Dockerfile --tag freitaas/api:latest
        docker build . --file ML/Dockerfile --tag freitaas/ml:latest
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push freitaas/api:latest
        docker push freitaas/ml:latest